install.packages("ggplot2")
library("ggplot2")
install.packages("palmerpenguins")
library("palmerpenguins")
ggplot(data = penguins) + geom_point(mapping = aes(x = flipper_length_mm, y = body_mass_g,color=species)) + facet_wrap(~species)
ggplot(data=diamonds)+geom_bar(mapping = aes(x=cut,fill = cut)) + facet_wrap(~cut)
ggplot(data=diamonds)+geom_bar(mapping = aes(x=color,fill = cut)) + facet_wrap(~cut)
ggplot(data = penguins) + geom_point(mapping = aes(x = flipper_length_mm, y = body_mass_g,color=species)) + facet_grid(sex~species)
ggplot(data = hotel_bookings) + geom_bar(mapping = aes(x = distribution_channel)) + facet_wrap(~deposit_type)